/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Проверка работоспособности
         * @description Возвращает `{"status": "ok"}`, когда API и его база данных работают. Токен **не нужен**.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Обзор доски: колонки и пороги голосования
         * @description Всё о доске, **кроме** самих карточек:
         *
         *     - `accept_threshold` / `reject_threshold`: сколько голосов в сумме переносят карточку в
         *       *accepted* / *rejected*;
         *     - `columns`: все пять колонок в порядке отображения и сколько карточек в каждой прямо сейчас;
         *     - `stream`: поток курса, которому принадлежит доска.
         *
         *     Потом загрузите карточки через `GET /api/cards` и сгруппируйте их по `card.column`.
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Все карточки доски
         * @description Все карточки доски со всем, что нужно для отрисовки: голоса, счёт, ваш голос
         *     (`my_vote`), число комментариев и автор.
         *
         *     **Чтобы нарисовать доску**, вызовите без фильтров и сгруппируйте карточки по `card.column`.
         *
         *     Все фильтры необязательные и сочетаются друг с другом. Они удобны в Swagger или для
         *     страницы пользователя (`author_id`).
         */
        get: operations["listCards"];
        put?: never;
        /**
         * Создать карточку
         * @description Публикует новую карточку от вашего имени. Обязательны только `title` и `type`.
         *
         *     `type` — `event`, `idea` или `question`. В *accepted* и *rejected* карточку переносят
         *     только голоса. `date` — Unix-время в секундах.
         *
         *     Ответ — `201 Created` с новой карточкой в том же формате, что и в `GET /api/cards`, так что
         *     её можно сразу добавить в состояние.
         */
        post: operations["createCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Одна карточка с комментариями
         * @description Те же поля, что и в списке, плюс `comments`: все комментарии, от старых к новым, каждый
         *     со своим автором. Подходит для страницы или модального окна карточки.
         */
        get: operations["getCard"];
        put?: never;
        post?: never;
        /**
         * Удалить свою карточку
         * @description Удаляет **вашу** карточку вместе с её голосами и комментариями. Ответ —
         *     `204 No Content` с **пустым телом**, так что не вызывайте на нём `response.json()`.
         */
        delete: operations["deleteCard"];
        options?: never;
        head?: never;
        /**
         * Изменить свою карточку
         * @description Изменяет **вашу** карточку. Отправляйте только поля, которые хотите поменять:
         *     пропущенные останутся как есть, а `null` очищает `description`, `preview` или `date`.
         *
         *     Смена `type` переносит карточку между колонками event, idea и question. Голоса при этом не
         *     меняются, так что принятая карточка останется принятой.
         */
        patch: operations["updateCard"];
        trace?: never;
    };
    "/api/cards/{card_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Проголосовать за карточку (за или против)
         * @description Ставит ваш голос на чужую карточку. У вас **один голос на карточку**:
         *
         *     - голос `up` поверх вашего `down` меняет голос, и счёт сдвигается на 2;
         *     - повтор того же голоса ничего не меняет (повторять безопасно);
         *     - голос за свою карточку — 403.
         *
         *     Ответ — обновлённая карточка, её можно сразу заменить в состоянии. Если счёт дошёл до
         *     порога, её `column` уже `accepted` или `rejected`.
         */
        put: operations["voteCard"];
        post?: never;
        /**
         * Отозвать свой голос
         * @description Забирает ваш голос. Если вы не голосовали, ничего не произойдёт. В любом случае ответ —
         *     обновлённая карточка (с `my_vote: null`).
         */
        delete: operations["removeVote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Комментарии к карточке
         * @description Все комментарии к карточке, от старых к новым. Они же есть в `GET /api/cards/{card_id}`.
         */
        get: operations["listCardComments"];
        put?: never;
        /**
         * Прокомментировать карточку
         * @description Добавляет комментарий к любой карточке на доске, включая ваши. Комментарии плоские:
         *     отвечать на комментарии нельзя. Ответ — `201 Created` с новым комментарием.
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить свой комментарий
         * @description Удаляет **ваш** комментарий. Ответ — `204 No Content` с пустым телом.
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        /**
         * Изменить свой комментарий
         * @description Заменяет текст **вашего** комментария. Его `updated_at` меняется, так что можно
         *     показывать «(изменено)», когда `updated_at` отличается от `created_at`.
         */
        patch: operations["updateComment"];
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ваш профиль
         * @description Кто вы в этом API, включая ваш личный `email` и `stream`.
         *
         *     Самый первый запрос создаёт профиль из вашего профиля на платформе курса (имя, email и
         *     аватар). После этого он ваш: меняйте его через `PATCH /api/me`.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить профиль
         * @description Изменяет ваш профиль. Отправляйте только поля, которые хотите поменять.
         *
         *     Сервер проверяет всё, так что это хороший ориентир для валидации в вашей форме:
         *
         *     - `name`: 1-80 символов, очистить нельзя.
         *     - `email`: корректный адрес, которым не пользуется другой участник (иначе **409** с
         *       `errors: [{"field": "email", "message": "Этот email уже занят"}]`).
         *     - `avatar_url`: ссылка на картинку http(s) или `data:image/...` URI.
         *     - `telegram`: 5-32 латинских буквы, цифры или подчёркивания; `@` необязателен.
         *     - `status` — до 100 символов, `bio` — до 1000.
         *
         *     Ничего из этого не меняет ваш профиль на платформе курса.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Участники доски
         * @description Все участники доски, по алфавиту.
         *
         *     В списке есть и однокурсники, которые ещё не обращались к API. Они показываются с именем и
         *     аватаром с платформы курса, пока не изменят профиль здесь.
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Один участник со счётчиками активности
         * @description Публичный профиль участника плюс `cards_count`, `comments_count` и `total_score` — для
         *     страницы пользователя. Его карточки: `GET /api/cards?author_id={user_id}`.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущие пороги голосования
         * @description Текущие пороги, общие для всех потоков.
         */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить пороги голосования
         * @description Задаёт `accept_threshold` и/или `reject_threshold`.
         *
         *     Принятие считается на лету, поэтому изменение **сразу применяется ко всем карточкам во всех
         *     потоках**. Если снизить порог принятия, много карточек может сразу оказаться в *accepted*.
         */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/api/admin/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Потоки и их активность
         * @description Все потоки, которые обращались к API, от старых к новым, со счётчиками активности.
         */
        get: operations["listStreams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить любую карточку (модерация)
         * @description Удаляет карточку из любого потока вместе с её голосами и комментариями.
         */
        delete: operations["adminDeleteCard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить любой комментарий (модерация)
         * @description Удаляет комментарий из любого потока.
         */
        delete: operations["adminDeleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminStream
         * @description Поток, который обращался к этому API, со счётчиками активности.
         */
        AdminStream: {
            /**
             * Id
             * @description Id потока на платформе или `null` для студентов без потока.
             */
            id: string | null;
            /**
             * Code
             * @description Код потока.
             * @example 26F
             */
            code: string | null;
            /**
             * Title
             * @description Название потока.
             * @example Осенний поток 2026
             */
            title: string | null;
            /**
             * Name
             * @description `title` или `code`.
             * @example Осенний поток 2026
             */
            name: string;
            /**
             * Members Count
             * @description Участники.
             * @example 17
             */
            members_count: number;
            /**
             * Cards Count
             * @description Карточки.
             * @example 42
             */
            cards_count: number;
            /**
             * Comments Count
             * @description Комментарии.
             * @example 120
             */
            comments_count: number;
            /**
             * Votes Count
             * @description Голоса.
             * @example 300
             */
            votes_count: number;
            /**
             * First Seen At
             * @description Когда появился первый студент потока: Unix-время в секундах.
             * @example 1789041600
             */
            first_seen_at: number;
        };
        /**
         * Board
         * @description Доска целиком: колонки, пороги голосования и ваш поток.
         */
        Board: {
            /** @description Поток, которому принадлежит доска (ваш). */
            stream: components["schemas"]["Stream"];
            /**
             * Accept Threshold
             * @description Карточка принята, когда `score >= accept_threshold`.
             * @example 5
             */
            accept_threshold: number;
            /**
             * Reject Threshold
             * @description Карточка отклонена, когда `score <= -reject_threshold`.
             * @example 5
             */
            reject_threshold: number;
            /**
             * Columns
             * @description Все пять колонок в порядке отображения: event, idea, question, accepted, rejected.
             */
            columns: components["schemas"]["BoardColumn"][];
            /**
             * Cards Count
             * @description Всего карточек на доске.
             * @example 8
             */
            cards_count: number;
            /**
             * Members Count
             * @description Сколько участников доски знает этот API.
             * @example 17
             */
            members_count: number;
        };
        /**
         * BoardColumn
         * @description Одна колонка доски.
         */
        BoardColumn: {
            /**
             * @description Id колонки — то же значение, что в `Card.column`.
             * @example idea
             */
            id: components["schemas"]["CardColumn"];
            /**
             * Title
             * @description Название для показа.
             * @example Идеи
             */
            title: string;
            /**
             * Description
             * @description Что попадает в эту колонку.
             * @example Предложения, за которые голосуют участники.
             */
            description: string;
            /**
             * Cards Count
             * @description Сколько карточек в ней прямо сейчас.
             * @example 3
             */
            cards_count: number;
        };
        /**
         * BoardSettings
         * @description Пороги голосования, общие для всех потоков.
         */
        BoardSettings: {
            /**
             * Accept Threshold
             * @description `score >= accept_threshold` — карточка принята.
             * @example 5
             */
            accept_threshold: number;
            /**
             * Reject Threshold
             * @description `score <= -reject_threshold` — карточка отклонена.
             * @example 5
             */
            reject_threshold: number;
            /**
             * Updated At
             * @description Когда их последний раз меняли: Unix-время в секундах.
             * @example 1789041600
             */
            updated_at: number;
        };
        /**
         * BoardSettingsUpdate
         * @description Новые пороги. Отправьте один или оба. Они сразу применяются ко всем карточкам во всех потоках.
         */
        BoardSettingsUpdate: {
            /**
             * Accept Threshold
             * @description Целое положительное число.
             * @example 3
             */
            accept_threshold?: number;
            /**
             * Reject Threshold
             * @description Целое положительное число.
             * @example 3
             */
            reject_threshold?: number;
        };
        /**
         * Card
         * @description Карточка на доске со всем, что нужно для отрисовки.
         *
         *     **В какой колонке?** Смотрите на `column`:
         *
         *     - `accepted`, когда `score >= accept_threshold`;
         *     - `rejected`, когда `score <= -reject_threshold`;
         *     - иначе — `type` карточки (`event`, `idea` или `question`).
         *
         *     Это считается заново при каждом запросе: если голоса изменятся, карточка переедет.
         */
        Card: {
            /**
             * Id
             * Format: uuid
             * @description Id карточки.
             * @example 3f8e9c1a-5b2d-4e7f-9a61-2c4b8d0e1f23
             */
            id: string;
            /**
             * Title
             * @description Заголовок карточки.
             * @example Тёмная тема для доски
             */
            title: string;
            /**
             * @description Тип карточки, который выбрал автор. Не меняется, когда карточку принимают или отклоняют.
             * @example idea
             */
            type: components["schemas"]["CardType"];
            /**
             * Description
             * @description Подробный текст или `null`.
             * @example Вечером глаза устают от белого фона. Давайте добавим переключатель темы!
             */
            description: string | null;
            /**
             * Preview
             * @description Картинка, которую можно сразу подставить в `<img src>`, или `null`.
             * @example https://picsum.photos/seed/itam/640/360
             */
            preview: string | null;
            /**
             * Date
             * @description Дата карточки: Unix-время в секундах (UTC) или `null`. Для показа: `new Date(card.date * 1000).toLocaleString("ru-RU")`.
             * @example 1791648000
             */
            date: number | null;
            /**
             * @description Колонка, в которой рисовать карточку (правила выше).
             * @example accepted
             */
            column: components["schemas"]["CardColumn"];
            /**
             * Is Accepted
             * @description `true`, когда счёт достиг порога принятия.
             * @example true
             */
            is_accepted: boolean;
            /**
             * Is Rejected
             * @description `true`, когда счёт опустился до минус порога отклонения.
             * @example false
             */
            is_rejected: boolean;
            /**
             * Upvotes
             * @description Сколько человек проголосовали `up`.
             * @example 6
             */
            upvotes: number;
            /**
             * Downvotes
             * @description Сколько человек проголосовали `down`.
             * @example 1
             */
            downvotes: number;
            /**
             * Votes Count
             * @description Всего голосов: `upvotes + downvotes`.
             * @example 7
             */
            votes_count: number;
            /**
             * Score
             * @description Счёт: `upvotes - downvotes`.
             * @example 5
             */
            score: number;
            /**
             * Votes To Accept
             * @description Сколько ещё голосов «за» (с учётом голосов «против») нужно для принятия: `max(0, accept_threshold - score)`. `0`, когда карточка принята.
             * @example 0
             */
            votes_to_accept: number;
            /**
             * Votes To Reject
             * @description Сколько ещё голосов «против» (с учётом голосов «за») приведут к отклонению: `max(0, score + reject_threshold)`. `0`, когда карточка отклонена.
             * @example 10
             */
            votes_to_reject: number;
            /**
             * Comments Count
             * @description Сколько у неё комментариев.
             * @example 2
             */
            comments_count: number;
            /**
             * @description Как проголосовали *вы*: `up`, `down` или `null`, если не голосовали. На ваших карточках всегда `null`: за них голосовать нельзя.
             * @example up
             */
            my_vote: components["schemas"]["VoteValue"] | null;
            /**
             * Is Mine
             * @description `true`, если автор — вы. Изменять и удалять карточку может только автор, и никто не может голосовать за свои карточки.
             * @example false
             */
            is_mine: boolean;
            /** @description Кто опубликовал карточку. */
            author: components["schemas"]["User"];
            /**
             * Created At
             * @description Когда опубликована: Unix-время в секундах.
             * @example 1789041600
             */
            created_at: number;
            /**
             * Updated At
             * @description Когда последний раз меняли её содержимое: Unix-время в секундах. Голоса и комментарии его не меняют.
             * @example 1789041600
             */
            updated_at: number;
        };
        /**
         * CardColumn
         * @description Колонка доски, в которой рисуется карточка.
         *
         *     `event`, `idea` и `question` повторяют `type` карточки. В `accepted` или
         *     `rejected` карточка переходит, когда её счёт достигает порога (см.
         *     `GET /api/board`), и сохраняет при этом свой исходный `type`.
         * @enum {string}
         */
        CardColumn: "event" | "idea" | "question" | "accepted" | "rejected";
        /**
         * CardCreate
         * @description Новая карточка. Обязательны только `title` и `type`.
         */
        CardCreate: {
            /**
             * Title
             * @description Заголовок, 1-120 символов. Пробелы в начале и в конце обрезаются.
             * @example Сходить на хакатон ITAM
             */
            title: string;
            /**
             * @description В какой колонке карточка появится: `event`, `idea` или `question`. Создать карточку сразу в `accepted` или `rejected` нельзя: туда её переносят только голоса.
             * @example idea
             */
            type: components["schemas"]["CardType"];
            /**
             * Description
             * @description Подробный текст, до 5000 символов. Пустая строка считается `null`.
             * @example Собираем команду из 3-4 человек, опыт не важен.
             */
            description?: string | null;
            /**
             * Preview
             * @description Картинка для карточки в виде строки: ссылка на изображение `https://...` или `data:image/...;base64,...` URI (например, из `FileReader.readAsDataURL`). До 300 000 символов, так что для больших картинок используйте ссылки. Пустая строка считается `null`.
             * @example https://picsum.photos/seed/itam/640/360
             */
            preview?: string | null;
            /**
             * Date
             * @description Необязательная дата: **Unix-время в секундах** (целое число, UTC). Удобно для событий. Из `<input type="datetime-local">` или `<input type="date">`: `Math.floor(new Date(input.value).getTime() / 1000)`. Миллисекунды (`Date.now()`, `getTime()`) не подойдут: сначала разделите их на 1000. Пустая строка считается `null`.
             * @example 1791648000
             */
            date?: number | null;
        };
        /**
         * CardDetail
         * @description Карточка с комментариями: все поля `Card` плюс `comments`.
         */
        CardDetail: {
            /**
             * Id
             * Format: uuid
             * @description Id карточки.
             * @example 3f8e9c1a-5b2d-4e7f-9a61-2c4b8d0e1f23
             */
            id: string;
            /**
             * Title
             * @description Заголовок карточки.
             * @example Тёмная тема для доски
             */
            title: string;
            /**
             * @description Тип карточки, который выбрал автор. Не меняется, когда карточку принимают или отклоняют.
             * @example idea
             */
            type: components["schemas"]["CardType"];
            /**
             * Description
             * @description Подробный текст или `null`.
             * @example Вечером глаза устают от белого фона. Давайте добавим переключатель темы!
             */
            description: string | null;
            /**
             * Preview
             * @description Картинка, которую можно сразу подставить в `<img src>`, или `null`.
             * @example https://picsum.photos/seed/itam/640/360
             */
            preview: string | null;
            /**
             * Date
             * @description Дата карточки: Unix-время в секундах (UTC) или `null`. Для показа: `new Date(card.date * 1000).toLocaleString("ru-RU")`.
             * @example 1791648000
             */
            date: number | null;
            /**
             * @description Колонка, в которой рисовать карточку (правила выше).
             * @example accepted
             */
            column: components["schemas"]["CardColumn"];
            /**
             * Is Accepted
             * @description `true`, когда счёт достиг порога принятия.
             * @example true
             */
            is_accepted: boolean;
            /**
             * Is Rejected
             * @description `true`, когда счёт опустился до минус порога отклонения.
             * @example false
             */
            is_rejected: boolean;
            /**
             * Upvotes
             * @description Сколько человек проголосовали `up`.
             * @example 6
             */
            upvotes: number;
            /**
             * Downvotes
             * @description Сколько человек проголосовали `down`.
             * @example 1
             */
            downvotes: number;
            /**
             * Votes Count
             * @description Всего голосов: `upvotes + downvotes`.
             * @example 7
             */
            votes_count: number;
            /**
             * Score
             * @description Счёт: `upvotes - downvotes`.
             * @example 5
             */
            score: number;
            /**
             * Votes To Accept
             * @description Сколько ещё голосов «за» (с учётом голосов «против») нужно для принятия: `max(0, accept_threshold - score)`. `0`, когда карточка принята.
             * @example 0
             */
            votes_to_accept: number;
            /**
             * Votes To Reject
             * @description Сколько ещё голосов «против» (с учётом голосов «за») приведут к отклонению: `max(0, score + reject_threshold)`. `0`, когда карточка отклонена.
             * @example 10
             */
            votes_to_reject: number;
            /**
             * Comments Count
             * @description Сколько у неё комментариев.
             * @example 2
             */
            comments_count: number;
            /**
             * @description Как проголосовали *вы*: `up`, `down` или `null`, если не голосовали. На ваших карточках всегда `null`: за них голосовать нельзя.
             * @example up
             */
            my_vote: components["schemas"]["VoteValue"] | null;
            /**
             * Is Mine
             * @description `true`, если автор — вы. Изменять и удалять карточку может только автор, и никто не может голосовать за свои карточки.
             * @example false
             */
            is_mine: boolean;
            /** @description Кто опубликовал карточку. */
            author: components["schemas"]["User"];
            /**
             * Created At
             * @description Когда опубликована: Unix-время в секундах.
             * @example 1789041600
             */
            created_at: number;
            /**
             * Updated At
             * @description Когда последний раз меняли её содержимое: Unix-время в секундах. Голоса и комментарии его не меняют.
             * @example 1789041600
             */
            updated_at: number;
            /**
             * Comments
             * @description Все комментарии, от старых к новым.
             */
            comments: components["schemas"]["Comment"][];
        };
        /**
         * CardSort
         * @description Порядок списка карточек.
         *
         *     - `new`: сначала новые (по умолчанию).
         *     - `old`: сначала старые.
         *     - `top`: сначала с наибольшим счётом; при равном счёте — сначала новые.
         * @enum {string}
         */
        CardSort: "new" | "old" | "top";
        /**
         * CardType
         * @description О чём карточка. Тип выбирает автор и может поменять его в любой момент.
         *
         *     - `event`: то, что происходит в определённый день: встреча, дедлайн, хакатон.
         *     - `idea`: предложение, за которое голосуют участники.
         *     - `question`: то, на что вы хотите получить ответ.
         * @enum {string}
         */
        CardType: "event" | "idea" | "question";
        /**
         * CardUpdate
         * @description Изменение вашей карточки. Отправляйте только поля, которые хотите поменять.
         *
         *     - Пропущенные поля остаются как есть.
         *     - `null` очищает `description`, `preview` или `date`.
         *     - `title` и `type` можно изменить, но нельзя очистить.
         *
         *     Смена `type` переносит карточку между колонками `event`, `idea` и
         *     `question`. На голоса это не влияет, так что принятая карточка остаётся
         *     принятой.
         */
        CardUpdate: {
            /**
             * Title
             * @description Заголовок, 1-120 символов.
             * @example Сходить на хакатон ITAM всей командой
             */
            title?: string;
            /**
             * @description Новый тип: `event`, `idea` или `question`.
             * @example event
             */
            type?: components["schemas"]["CardType"];
            /**
             * Description
             * @description Подробный текст, до 5000 символов, или `null`, чтобы его очистить.
             */
            description?: string | null;
            /**
             * Preview
             * @description Картинка для карточки в виде строки: ссылка на изображение `https://...` или `data:image/...;base64,...` URI (например, из `FileReader.readAsDataURL`). До 300 000 символов, так что для больших картинок используйте ссылки. Пустая строка считается `null`.
             */
            preview?: string | null;
            /**
             * Date
             * @description Необязательная дата: **Unix-время в секундах** (целое число, UTC). Удобно для событий. Из `<input type="datetime-local">` или `<input type="date">`: `Math.floor(new Date(input.value).getTime() / 1000)`. Миллисекунды (`Date.now()`, `getTime()`) не подойдут: сначала разделите их на 1000. Пустая строка считается `null`.
             * @example 1791648000
             */
            date?: number | null;
        };
        /**
         * Comment
         * @description Комментарий к карточке. Комментарии плоские: ответить на комментарий нельзя.
         */
        Comment: {
            /**
             * Id
             * Format: uuid
             * @description Id комментария.
             * @example 3f8e9c1a-5b2d-4e7f-9a61-2c4b8d0e1f23
             */
            id: string;
            /**
             * Card Id
             * Format: uuid
             * @description Карточка, к которой он относится.
             * @example 3f8e9c1a-5b2d-4e7f-9a61-2c4b8d0e1f23
             */
            card_id: string;
            /**
             * Text
             * @description Текст комментария.
             * @example Буду! А запись будет?
             */
            text: string;
            /** @description Кто написал. */
            author: components["schemas"]["User"];
            /**
             * Is Mine
             * @description `true`, если его написали вы, — значит, вы можете его изменить или удалить.
             * @example false
             */
            is_mine: boolean;
            /**
             * Created At
             * @description Когда опубликован: Unix-время в секундах.
             * @example 1789041600
             */
            created_at: number;
            /**
             * Updated At
             * @description Когда последний раз изменён: Unix-время в секундах. Равен `created_at`, если комментарий не редактировали.
             * @example 1789041600
             */
            updated_at: number;
        };
        /**
         * CommentCreate
         * @description Новый комментарий.
         */
        CommentCreate: {
            /**
             * Text
             * @description Текст комментария, 1-2000 символов.
             * @example Классная идея, я за!
             */
            text: string;
        };
        /**
         * CommentUpdate
         * @description Новый текст вашего комментария.
         */
        CommentUpdate: {
            /**
             * Text
             * @description Текст комментария, 1-2000 символов.
             * @example Классная идея, я за! (upd: уже проголосовал)
             */
            text: string;
        };
        /**
         * ErrorResponse
         * @description Так выглядит любой ответ с ошибкой.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Что пошло не так — предложение, которое можно показать человеку.
             * @example Карточка не найдена. Возможно, её удалили.
             */
            detail: string;
        };
        /**
         * FieldError
         * @description Проблема с одним конкретным полем.
         */
        FieldError: {
            /**
             * Field
             * @description К чему относится проблема: к полю тела запроса (`title`, `email`; вложенные поля пишутся через точку, например `items.0.name`), к query- или path-параметру или к телу запроса целиком (`body`).
             * @example title
             */
            field: string;
            /**
             * Message
             * @description Что не так. Покажите это рядом с соответствующим полем формы.
             * @example Обязательное поле
             */
            message: string;
        };
        /**
         * Health
         * @description Состояние сервиса.
         */
        Health: {
            /**
             * Status
             * @description `ok`, когда API и его база данных работают.
             * @example ok
             */
            status: string;
        };
        /**
         * Profile
         * @description Ваш профиль.
         *
         *     Изначально в нём имя, email и аватар с платформы курса. Дальше он
         *     принадлежит вам: изменения здесь не затрагивают платформу, а изменения на
         *     платформе не перезаписывают его.
         */
        Profile: {
            /**
             * Id
             * Format: uuid
             * @description Ваш id в этом API.
             * @example 3f8e9c1a-5b2d-4e7f-9a61-2c4b8d0e1f23
             */
            id: string;
            /**
             * Name
             * @description Отображаемое имя.
             * @example Аня Петрова
             */
            name: string;
            /**
             * Email
             * @description Ваш email. Его видите только вы. Он не должен совпадать с email другого участника.
             * @example anya@example.com
             */
            email: string | null;
            /**
             * Avatar Url
             * @description Аватар: ссылка на картинку http(s) или `data:image/...` URI.
             * @example https://courses.salut.uno/api/v1/media/avatars/anya.png
             */
            avatar_url: string | null;
            /**
             * Status
             * @description Короткий статус.
             * @example Ищу команду на хакатон
             */
            status: string | null;
            /**
             * Bio
             * @description О себе.
             * @example Учу React по вечерам.
             */
            bio: string | null;
            /**
             * Telegram
             * @description Имя пользователя в Telegram без `@`.
             * @example anya_codes
             */
            telegram: string | null;
            /** @description Поток, в котором вы учитесь. */
            stream: components["schemas"]["Stream"];
            /**
             * Created At
             * @description Когда вы впервые обратились к этому API: Unix-время в секундах.
             * @example 1789041600
             */
            created_at: number;
            /**
             * Updated At
             * @description Когда профиль последний раз меняли: Unix-время в секундах.
             * @example 1789041600
             */
            updated_at: number;
        };
        /**
         * ProfileUpdate
         * @description Изменение профиля. Отправляйте только поля, которые хотите поменять.
         *
         *     - Пропущенные поля остаются как есть.
         *     - `null` (или пустая строка) очищает необязательное поле.
         *     - `name` можно изменить, но нельзя очистить.
         */
        ProfileUpdate: {
            /**
             * Name
             * @description Отображаемое имя, 1-80 символов.
             * @example Аня Петрова
             */
            name?: string;
            /**
             * Email
             * @description Корректный email, не занятый другим участником. Если он уже занят, придёт 409 `Этот email уже занят`.
             * @example anya@example.com
             */
            email?: string | null;
            /**
             * Avatar Url
             * @description Ссылка на картинку http(s) или `data:image/...;base64,...` URI, до 150 000 символов. Аватар показывается на каждой вашей карточке и в каждом комментарии, так что пусть он будет небольшим.
             * @example https://i.pravatar.cc/150?img=5
             */
            avatar_url?: string | null;
            /**
             * Status
             * @description Короткий статус, до 100 символов.
             * @example Ищу команду на хакатон
             */
            status?: string | null;
            /**
             * Bio
             * @description О себе, до 1000 символов.
             * @example Учу React по вечерам.
             */
            bio?: string | null;
            /**
             * Telegram
             * @description Имя пользователя в Telegram: 5-32 латинских буквы, цифры или подчёркивания. `@` в начале необязателен и отбрасывается.
             * @example @anya_codes
             */
            telegram?: string | null;
        };
        /**
         * Stream
         * @description Поток курса, в котором вы учитесь.
         */
        Stream: {
            /**
             * Id
             * @description Id потока на платформе курса. `null`, если вы записаны на курс без потока.
             * @example 7c2a41e0-93d4-4b8e-8f0c-5a1d2e3f4b5c
             */
            id: string | null;
            /**
             * Code
             * @description Короткий код потока.
             * @example 26F
             */
            code: string | null;
            /**
             * Title
             * @description Название от команды курса. Часто `null`, поэтому для показа берите `name`.
             * @example Осенний поток 2026
             */
            title: string | null;
            /**
             * Name
             * @description Готовое для показа название: `title`, а если его нет — `code`.
             * @example Осенний поток 2026
             */
            name: string;
        };
        /**
         * User
         * @description Участник, каким его видят остальные.
         *
         *     Используется как автор карточек и комментариев и в списке участников.
         *     Email — личные данные: он есть только в вашем собственном `Profile`.
         */
        User: {
            /**
             * Id
             * Format: uuid
             * @description Id пользователя в этом API. Используйте его в `GET /api/users/{user_id}` и `GET /api/cards?author_id=...`.
             * @example 3f8e9c1a-5b2d-4e7f-9a61-2c4b8d0e1f23
             */
            id: string;
            /**
             * Name
             * @description Отображаемое имя.
             * @example Аня Петрова
             */
            name: string;
            /**
             * Avatar Url
             * @description Аватар в виде строки, которую можно сразу подставить в `<img src>`: ссылка http(s) или `data:image/...` URI. `null` — аватара нет, покажите инициалы.
             * @example https://courses.salut.uno/api/v1/media/avatars/anya.png
             */
            avatar_url: string | null;
            /**
             * Status
             * @description Короткий статус, как в мессенджере.
             * @example Ищу команду на хакатон
             */
            status: string | null;
            /**
             * Bio
             * @description Пара слов о себе.
             * @example Учу React по вечерам.
             */
            bio: string | null;
            /**
             * Telegram
             * @description Имя пользователя в Telegram без `@`.
             * @example anya_codes
             */
            telegram: string | null;
            /**
             * Is Me
             * @description `true`, если это вы.
             * @example false
             */
            is_me: boolean;
            /**
             * Created At
             * @description Когда пользователь впервые появился в этом API: Unix-время в секундах.
             * @example 1789041600
             */
            created_at: number;
        };
        /**
         * UserDetail
         * @description Участник со счётчиками активности.
         */
        UserDetail: {
            /**
             * Id
             * Format: uuid
             * @description Id пользователя в этом API. Используйте его в `GET /api/users/{user_id}` и `GET /api/cards?author_id=...`.
             * @example 3f8e9c1a-5b2d-4e7f-9a61-2c4b8d0e1f23
             */
            id: string;
            /**
             * Name
             * @description Отображаемое имя.
             * @example Аня Петрова
             */
            name: string;
            /**
             * Avatar Url
             * @description Аватар в виде строки, которую можно сразу подставить в `<img src>`: ссылка http(s) или `data:image/...` URI. `null` — аватара нет, покажите инициалы.
             * @example https://courses.salut.uno/api/v1/media/avatars/anya.png
             */
            avatar_url: string | null;
            /**
             * Status
             * @description Короткий статус, как в мессенджере.
             * @example Ищу команду на хакатон
             */
            status: string | null;
            /**
             * Bio
             * @description Пара слов о себе.
             * @example Учу React по вечерам.
             */
            bio: string | null;
            /**
             * Telegram
             * @description Имя пользователя в Telegram без `@`.
             * @example anya_codes
             */
            telegram: string | null;
            /**
             * Is Me
             * @description `true`, если это вы.
             * @example false
             */
            is_me: boolean;
            /**
             * Created At
             * @description Когда пользователь впервые появился в этом API: Unix-время в секундах.
             * @example 1789041600
             */
            created_at: number;
            /**
             * Cards Count
             * @description Сколько карточек опубликовал.
             * @example 4
             */
            cards_count: number;
            /**
             * Comments Count
             * @description Сколько комментариев написал.
             * @example 11
             */
            comments_count: number;
            /**
             * Total Score
             * @description Сумма счёта всех его карточек.
             * @example 7
             */
            total_score: number;
        };
        /**
         * ValidationErrorResponse
         * @description Приходит с 422 (некорректные данные) и некоторыми 409 (например, когда email уже занят).
         *
         *     `detail` собирает все проблемы в одно предложение, а `errors` перечисляет
         *     их по одной, чтобы форма могла подсветить нужные поля.
         */
        ValidationErrorResponse: {
            /**
             * Detail
             * @description Все проблемы одним читаемым предложением.
             * @example title: Обязательное поле; type: Допустимые значения: 'event', 'idea', 'question'
             */
            detail: string;
            /**
             * Errors
             * @description Те же проблемы, по одной на поле.
             */
            errors: components["schemas"]["FieldError"][];
        };
        /**
         * VoteRequest
         * @description Ваш голос. Если отправить его ещё раз с другим значением, голос поменяется.
         */
        VoteRequest: {
            /**
             * @description `up` или `down`.
             * @example up
             */
            value: components["schemas"]["VoteValue"];
        };
        /**
         * VoteValue
         * @description Голос за карточку: `up` добавляет к её счёту 1, `down` отнимает 1.
         * @enum {string}
         */
        VoteValue: "up" | "down";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description База данных недоступна. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listCards: {
        parameters: {
            query?: {
                /** @description Только карточки, которые сейчас в этой колонке. */
                column?: components["schemas"]["CardColumn"] | null;
                /** @description Только карточки этого типа. Принятые и отклонённые карточки сохраняют свой тип. */
                type?: components["schemas"]["CardType"] | null;
                /** @description Только карточки этого пользователя. Для «моих карточек» возьмите свой id из `GET /api/me`. */
                author_id?: string | null;
                /** @description Поиск по заголовку и описанию без учёта регистра. */
                q?: string | null;
                /** @description Порядок списка. */
                sort?: components["schemas"]["CardSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"][];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Успешный ответ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id карточки. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный параметр, например id — не UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id карточки. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Это действие вам недоступно. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный параметр, например id — не UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id карточки. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Это действие вам недоступно. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    voteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id карточки. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteRequest"];
            };
        };
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Это действие вам недоступно. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id карточки. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный параметр, например id — не UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listCardComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id карточки. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный параметр, например id — не UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id карточки. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreate"];
            };
        };
        responses: {
            /** @description Успешный ответ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id комментария. */
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Это действие вам недоступно. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный параметр, например id — не UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id комментария. */
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdate"];
            };
        };
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Это действие вам недоступно. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Этот email уже использует другой участник. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Поиск по имени без учёта регистра. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id пользователя, например `card.author.id`. */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            /** @description Заголовка `X-Course-Token` нет или токен недействителен. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный параметр, например id — не UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Слишком много запросов с этого токена. Подождите `Retry-After` секунд. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Платформа курса недоступна, поэтому токен не проверить. Повторите запрос чуть позже. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSettings"];
                };
            };
            /** @description Нет заголовка `X-Admin-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неверный админский токен. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Админский API не настроен на этом сервере. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardSettingsUpdate"];
            };
        };
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSettings"];
                };
            };
            /** @description Нет заголовка `X-Admin-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неверный админский токен. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректные данные. В `errors` перечислены все проблемы, по одной на поле. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Админский API не настроен на этом сервере. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listStreams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStream"][];
                };
            };
            /** @description Нет заголовка `X-Admin-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неверный админский токен. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Админский API не настроен на этом сервере. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminDeleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id карточки. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет заголовка `X-Admin-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неверный админский токен. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный параметр, например id — не UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Админский API не настроен на этом сервере. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminDeleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id комментария. */
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успешный ответ */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет заголовка `X-Admin-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Неверный админский токен. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Не найдено: такого объекта нет или его удалили. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный параметр, например id — не UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Админский API не настроен на этом сервере. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
